// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orsuun.Server.Data;

#nullable disable

namespace Orsuun.Server.Migrations
{
    [DbContext(typeof(GameDb))]
    [Migration("20260928132810_FishHook")]
    partial class FishHook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orsuun.Server.Data.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AnvilWards")
                        .HasColumnType("integer");

                    b.Property<bool>("AtRiver")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AutoFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AutoRodUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BanReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("BannedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Banner")
                        .HasColumnType("integer");

                    b.Property<string>("Blocked")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("BoardWeek")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("BoardWeekStage")
                        .HasColumnType("integer");

                    b.Property<long>("BoardWeekXp")
                        .HasColumnType("bigint");

                    b.Property<string>("Bounties")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("CastBiteMs")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CastUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Class")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DungeonDay")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("DungeonPausedId")
                        .HasColumnType("integer");

                    b.Property<long>("DungeonRunAtSmith")
                        .HasColumnType("bigint");

                    b.Property<int>("DungeonRuns")
                        .HasColumnType("integer");

                    b.Property<int>("EtchingNeedles")
                        .HasColumnType("integer");

                    b.Property<string>("Feats")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FeatsClaimed")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Figure")
                        .HasColumnType("integer");

                    b.Property<string>("Fish")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("GuildDonated")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildDonatedToday")
                        .HasColumnType("bigint");

                    b.Property<string>("GuildDonationDay")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("GuildId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuildJoinedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GuildRank")
                        .HasColumnType("integer");

                    b.Property<int>("HighestStageCleared")
                        .HasColumnType("integer");

                    b.Property<long>("Honor")
                        .HasColumnType("bigint");

                    b.Property<int>("HookedFish")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HookedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("HuntCarryTicks")
                        .HasColumnType("bigint");

                    b.Property<int>("HuntEncounter")
                        .HasColumnType("integer");

                    b.Property<int>("HuntMarks")
                        .HasColumnType("integer");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<bool>("InviteRewarded")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("InvitedById")
                        .HasColumnType("uuid");

                    b.Property<int>("KhansAlloys")
                        .HasColumnType("integer");

                    b.Property<string>("Korshards")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("LaneLoop")
                        .HasColumnType("integer");

                    b.Property<long>("LaneSeed")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastChatUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSiegeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Laurels")
                        .HasColumnType("integer");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uuid");

                    b.Property<int>("MastersNeedles")
                        .HasColumnType("integer");

                    b.Property<int>("Materials")
                        .HasColumnType("integer");

                    b.Property<string>("Meals")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<int>("Mussels")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("MutedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("Oathstones")
                        .HasColumnType("integer");

                    b.Property<int>("ParkedStage")
                        .HasColumnType("integer");

                    b.Property<string>("Pearls")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("PinningWax")
                        .HasColumnType("integer");

                    b.Property<string>("PitDay")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("PitFights")
                        .HasColumnType("integer");

                    b.Property<int>("PitLastLaurels")
                        .HasColumnType("integer");

                    b.Property<int>("PitLastRank")
                        .HasColumnType("integer");

                    b.Property<int>("PitLastRating")
                        .HasColumnType("integer");

                    b.Property<string>("PitLastSeason")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("PitLosses")
                        .HasColumnType("integer");

                    b.Property<int>("PitRating")
                        .HasColumnType("integer");

                    b.Property<int>("PitRoll")
                        .HasColumnType("integer");

                    b.Property<string>("PitSeason")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("PitSeasonLosses")
                        .HasColumnType("integer");

                    b.Property<int>("PitSeasonWins")
                        .HasColumnType("integer");

                    b.Property<string>("PitTitle")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("PitWins")
                        .HasColumnType("integer");

                    b.Property<int>("Potions")
                        .HasColumnType("integer");

                    b.Property<int>("Renewals")
                        .HasColumnType("integer");

                    b.Property<int>("ScrollsOfMercy")
                        .HasColumnType("integer");

                    b.Property<string>("SessionToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SkillGrades")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SkillProgress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SkillReads")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Skins")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<long>("Sorn")
                        .HasColumnType("bigint");

                    b.Property<int>("SummoningMarkers")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SwornUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tallies")
                        .HasColumnType("integer");

                    b.Property<int>("TitleId")
                        .HasColumnType("integer");

                    b.Property<string>("Trail")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<int>("Turnstones")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Wardrobe")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("WeaponsBroken")
                        .HasColumnType("integer");

                    b.Property<string>("WornCompanion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WornMount")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WornSkin")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeviceToken")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasFilter("\"InviteCode\" <> ''");

                    b.HasIndex("InvitedById");

                    b.HasIndex("LoginId");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasFilter("\"NameKey\" <> ''");

                    b.HasIndex("PitRating");

                    b.HasIndex("SessionToken");

                    b.HasIndex("CreatedIp", "CreatedUtc");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Orsuun.Server.Data.AdminAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Admin")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Utc");

                    b.ToTable("AdminActions");
                });

            modelBuilder.Entity("Orsuun.Server.Data.BannerScore", b =>
                {
                    b.Property<string>("Season")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Banner")
                        .HasColumnType("integer");

                    b.Property<long>("Points")
                        .HasColumnType("bigint");

                    b.HasKey("Season", "Banner");

                    b.ToTable("BannerScores");
                });

            modelBuilder.Entity("Orsuun.Server.Data.BookStack", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.HasKey("AccountId", "BookId");

                    b.ToTable("BookStacks");
                });

            modelBuilder.Entity("Orsuun.Server.Data.BossClock", b =>
                {
                    b.Property<int>("BossId")
                        .HasColumnType("integer");

                    b.Property<long>("HpLeft")
                        .HasColumnType("bigint");

                    b.Property<long>("HpMax")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PoolSpawnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SlainBanner")
                        .HasColumnType("integer");

                    b.Property<string>("SlainBy")
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<DateTime?>("SlainUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SpawnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BossId");

                    b.ToTable("BossClocks");
                });

            modelBuilder.Entity("Orsuun.Server.Data.BossHit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Banner")
                        .HasColumnType("integer");

                    b.Property<int>("BossId")
                        .HasColumnType("integer");

                    b.Property<long>("Damage")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<DateTime>("SpawnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BossId", "SpawnUtc");

                    b.ToTable("BossHits");
                });

            modelBuilder.Entity("Orsuun.Server.Data.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Banner")
                        .HasColumnType("integer");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(56)
                        .HasColumnType("character varying(56)");

                    b.Property<int>("Reports")
                        .HasColumnType("integer");

                    b.Property<bool>("Reviewed")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Channel", "Id");

                    b.HasIndex("Reports", "Reviewed");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Orsuun.Server.Data.ChatReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MessageId", "ReporterId")
                        .IsUnique();

                    b.ToTable("ChatReports");
                });

            modelBuilder.Entity("Orsuun.Server.Data.ClientLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Stack")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Utc");

                    b.ToTable("ClientLogs");
                });

            modelBuilder.Entity("Orsuun.Server.Data.Device", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Token");

                    b.HasIndex("AccountId");

                    b.HasIndex("LoginId");

                    b.HasIndex("SessionToken");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Orsuun.Server.Data.DungeonRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("DungeonId")
                        .HasColumnType("integer");

                    b.Property<int>("FloorsCleared")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "State");

                    b.ToTable("DungeonRuns");
                });

            modelBuilder.Entity("Orsuun.Server.Data.ExternalLogin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("LoginId");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique();

                    b.ToTable("ExternalLogins");
                });

            modelBuilder.Entity("Orsuun.Server.Data.Fortress", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FlagGuildId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HeldSinceUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Holder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("KeepEndsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("KeepMended")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("KeepStartsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KeepState")
                        .HasColumnType("integer");

                    b.Property<string>("KeepWeek")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("LastEvent")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<long>("SiegeEmber")
                        .HasColumnType("bigint");

                    b.Property<long>("SiegeGold")
                        .HasColumnType("bigint");

                    b.Property<long>("SiegeSky")
                        .HasColumnType("bigint");

                    b.Property<long>("Wall")
                        .HasColumnType("bigint");

                    b.Property<long>("WallMax")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Fortresses");
                });

            modelBuilder.Entity("Orsuun.Server.Data.FortressBid", b =>
                {
                    b.Property<string>("Week")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<bool>("Contender")
                        .HasColumnType("boolean");

                    b.Property<long>("Damage")
                        .HasColumnType("bigint");

                    b.Property<int>("FortressId")
                        .HasColumnType("integer");

                    b.Property<bool>("Refunded")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Week", "GuildId");

                    b.HasIndex("Week", "FortressId");

                    b.ToTable("FortressBids");
                });

            modelBuilder.Entity("Orsuun.Server.Data.Friendship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FromId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ToId");

                    b.HasIndex("FromId", "ToId")
                        .IsUnique();

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("Orsuun.Server.Data.Guild", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEvent")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Muster")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("Open")
                        .HasColumnType("boolean");

                    b.Property<int>("Plunder")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<long>("Treasury")
                        .HasColumnType("bigint");

                    b.Property<int>("WarDraws")
                        .HasColumnType("integer");

                    b.Property<int>("WarLosses")
                        .HasColumnType("integer");

                    b.Property<int>("WarRating")
                        .HasColumnType("integer");

                    b.Property<int>("WarWins")
                        .HasColumnType("integer");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NameKey")
                        .IsUnique();

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.HasIndex("Xp");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Orsuun.Server.Data.GuildInvite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InviterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("GuildId", "AccountId")
                        .IsUnique();

                    b.ToTable("GuildInvites");
                });

            modelBuilder.Entity("Orsuun.Server.Data.GuildRaid", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("EndsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid");

                    b.Property<long>("HpLeft")
                        .HasColumnType("bigint");

                    b.Property<long>("HpMax")
                        .HasColumnType("bigint");

                    b.Property<int>("Map")
                        .HasColumnType("integer");

                    b.Property<int>("Members")
                        .HasColumnType("integer");

                    b.Property<string>("SlainBy")
                        .IsRequired()
                        .HasMaxLength(56)
                        .HasColumnType("character varying(56)");

                    b.Property<DateTime?>("SlainUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Week")
                        .IsUnique();

                    b.ToTable("GuildRaids");
                });

            modelBuilder.Entity("Orsuun.Server.Data.GuildRaidHit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<long>("Damage")
                        .HasColumnType("bigint");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(56)
                        .HasColumnType("character varying(56)");

                    b.Property<long>("RaidId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RaidId", "AccountId", "Day");

                    b.ToTable("GuildRaidHits");
                });

            modelBuilder.Entity("Orsuun.Server.Data.GuildRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("GuildId", "AccountId")
                        .IsUnique();

                    b.ToTable("GuildRequests");
                });

            modelBuilder.Entity("Orsuun.Server.Data.GuildWar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("EndsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FlagA")
                        .HasColumnType("integer");

                    b.Property<int>("FlagB")
                        .HasColumnType("integer");

                    b.Property<int>("Front0")
                        .HasColumnType("integer");

                    b.Property<int>("Front1")
                        .HasColumnType("integer");

                    b.Property<int>("Front2")
                        .HasColumnType("integer");

                    b.Property<Guid>("GuildA")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuildB")
                        .HasColumnType("uuid");

                    b.Property<int>("KillsA")
                        .HasColumnType("integer");

                    b.Property<int>("KillsB")
                        .HasColumnType("integer");

                    b.Property<string>("LastEvent")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Night")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Night", "GuildA");

                    b.HasIndex("Night", "GuildB");

                    b.HasIndex("Result", "EndsUtc");

                    b.ToTable("GuildWars");
                });

            modelBuilder.Entity("Orsuun.Server.Data.GuildWarEntry", b =>
                {
                    b.Property<long>("WarId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Fights")
                        .HasColumnType("integer");

                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("WarId", "AccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("GuildWarEntries");
                });

            modelBuilder.Entity("Orsuun.Server.Data.GuildWarNight", b =>
                {
                    b.Property<string>("Night")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime>("EndsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Paired")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Night");

                    b.ToTable("GuildWarNights");
                });

            modelBuilder.Entity("Orsuun.Server.Data.GuildWarSignup", b =>
                {
                    b.Property<string>("Night")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Night", "GuildId");

                    b.ToTable("GuildWarSignups");
                });

            modelBuilder.Entity("Orsuun.Server.Data.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AverageDamage")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepotLoginId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Destroyed")
                        .HasColumnType("boolean");

                    b.Property<bool>("Equipped")
                        .HasColumnType("boolean");

                    b.Property<string>("Etchings")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("InMail")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("Listed")
                        .HasColumnType("boolean");

                    b.Property<int>("LockedEtchingIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("PatienceBp")
                        .HasColumnType("integer");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("SkillDamage")
                        .HasColumnType("integer");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<string>("Sockets")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("TradeId")
                        .HasColumnType("bigint");

                    b.Property<int>("UpgradeLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepotLoginId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Orsuun.Server.Data.LedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SornDelta")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "RequestId")
                        .IsUnique();

                    b.HasIndex("AccountId", "Utc");

                    b.ToTable("Ledger");
                });

            modelBuilder.Entity("Orsuun.Server.Data.Letter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("BookCount")
                        .HasColumnType("integer");

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("GoodCount")
                        .HasColumnType("integer");

                    b.Property<int>("GoodId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("Read")
                        .HasColumnType("boolean");

                    b.Property<long>("Sorn")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("TakenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Id");

                    b.HasIndex("AccountId", "Read");

                    b.ToTable("Letters");
                });

            modelBuilder.Entity("Orsuun.Server.Data.Login", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("Amber")
                        .HasColumnType("bigint");

                    b.Property<int>("AmberPurchases")
                        .HasColumnType("integer");

                    b.Property<int>("Banner")
                        .HasColumnType("integer");

                    b.Property<string>("BannerChangedSeason")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("CreatedIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DailyClaimedOn")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("DailyDay")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ResetHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ResetTries")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResetUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SwornUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerifyHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("VerifyUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("CreatedIp", "CreatedUtc");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("Orsuun.Server.Data.MarketListing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BookCount")
                        .HasColumnType("integer");

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GoodCount")
                        .HasColumnType("integer");

                    b.Property<int>("GoodId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("ItemLevel")
                        .HasColumnType("integer");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("SellerBanner")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasMaxLength(56)
                        .HasColumnType("character varying(56)");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UpgradeLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("SellerId", "Status");

                    b.HasIndex("Status", "ClosedUtc");

                    b.HasIndex("Status", "ExpiresUtc");

                    b.HasIndex("Status", "Slot", "Price");

                    b.ToTable("MarketListings");
                });

            modelBuilder.Entity("Orsuun.Server.Data.Milestone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique();

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("Orsuun.Server.Data.NameReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Reviewed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Reviewed");

                    b.HasIndex("Kind", "TargetId", "Name", "ReporterId")
                        .IsUnique();

                    b.ToTable("NameReports");
                });

            modelBuilder.Entity("Orsuun.Server.Data.PitSeasonRecord", b =>
                {
                    b.Property<string>("Season")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Champions")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Fighters")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SettledUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Season");

                    b.ToTable("PitSeasons");
                });

            modelBuilder.Entity("Orsuun.Server.Data.PrivateMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("FromId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Read")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ToId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ToId", "Read");

                    b.HasIndex("FromId", "ToId", "Id");

                    b.ToTable("PrivateMessages");
                });

            modelBuilder.Entity("Orsuun.Server.Data.Purchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<long>("Amber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Sandbox")
                        .HasColumnType("boolean");

                    b.Property<string>("Store")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LoginId");

                    b.HasIndex("Store", "TransactionId")
                        .IsUnique();

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Orsuun.Server.Data.PushToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uuid");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<bool>("Sandbox")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LoginId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("PushTokens");
                });

            modelBuilder.Entity("Orsuun.Server.Data.TradeSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosedReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ClosedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromBooks")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("FromId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromItems")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<long>("FromSorn")
                        .HasColumnType("bigint");

                    b.Property<int>("FromStep")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("ToBooks")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ToId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToItems")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<long>("ToSorn")
                        .HasColumnType("bigint");

                    b.Property<int>("ToStep")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TouchedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FromId", "State");

                    b.HasIndex("ToId", "State");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("Orsuun.Server.Data.WorldEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Announced")
                        .HasColumnType("boolean");

                    b.Property<string>("By")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("EndsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartsUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Weekly")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EndsUtc");

                    b.HasIndex("Kind", "StartsUtc")
                        .IsUnique();

                    b.ToTable("WorldEvents");
                });

            modelBuilder.Entity("Orsuun.Server.Data.BookStack", b =>
                {
                    b.HasOne("Orsuun.Server.Data.Account", null)
                        .WithMany("Books")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orsuun.Server.Data.Item", b =>
                {
                    b.HasOne("Orsuun.Server.Data.Account", null)
                        .WithMany("Items")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orsuun.Server.Data.Account", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
