// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orsuun.Server.Data;

#nullable disable

namespace Orsuun.Server.Migrations
{
    [DbContext(typeof(GameDb))]
    [Migration("20260923114100_AccountCreatedIp")]
    partial class AccountCreatedIp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orsuun.Server.Data.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AnvilWards")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("EtchingNeedles")
                        .HasColumnType("integer");

                    b.Property<int>("HighestStageCleared")
                        .HasColumnType("integer");

                    b.Property<int>("KhansAlloys")
                        .HasColumnType("integer");

                    b.Property<string>("Korshards")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Materials")
                        .HasColumnType("integer");

                    b.Property<int>("ParkedStage")
                        .HasColumnType("integer");

                    b.Property<int>("Potions")
                        .HasColumnType("integer");

                    b.Property<int>("ScrollsOfMercy")
                        .HasColumnType("integer");

                    b.Property<string>("SessionToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Skins")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("Sorn")
                        .HasColumnType("bigint");

                    b.Property<int>("SummoningMarkers")
                        .HasColumnType("integer");

                    b.Property<int>("Turnstones")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("WeaponsBroken")
                        .HasColumnType("integer");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DeviceToken")
                        .IsUnique();

                    b.HasIndex("SessionToken");

                    b.HasIndex("CreatedIp", "CreatedUtc");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Orsuun.Server.Data.BossClock", b =>
                {
                    b.Property<int>("BossId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SpawnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BossId");

                    b.ToTable("BossClocks");
                });

            modelBuilder.Entity("Orsuun.Server.Data.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Destroyed")
                        .HasColumnType("boolean");

                    b.Property<bool>("Equipped")
                        .HasColumnType("boolean");

                    b.Property<string>("Etchings")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ItemLevel")
                        .HasColumnType("integer");

                    b.Property<int>("LockedEtchingIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("PatienceBp")
                        .HasColumnType("integer");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<string>("Sockets")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("UpgradeLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Orsuun.Server.Data.LedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SornDelta")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Utc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "RequestId")
                        .IsUnique();

                    b.HasIndex("AccountId", "Utc");

                    b.ToTable("Ledger");
                });

            modelBuilder.Entity("Orsuun.Server.Data.Item", b =>
                {
                    b.HasOne("Orsuun.Server.Data.Account", null)
                        .WithMany("Items")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orsuun.Server.Data.Account", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
